name = Cultura Viva Layout
description = Un layout para usar como home en Encuentro Cultura Viva
preview = preview.png
template = cultura_viva-layout

regions[principal]		= Barra Superior
regions[branding]       = Marca
regions[slider]			= Slider
regions[highlighted]    = Destacado
regions[help]           = Ayuda
regions[content]        = Contenido
regions[sidebar_first] 	= Lateral
regions[no_logo]        = No Logo
regions[footer]         = Footer


; Stylesheets
stylesheets[all][] = css/layouts/ecv/culturaviva.layout.css
stylesheets[all][] = css/layouts/ecv/culturaviva.layout.no-query.css
stylesheets[all][] = css/layouts/ecv/culturaviva-home.layout.css
