name = Home Verde Chile
description = Un layout para usar como home
preview = preview.png
template = home_verdechile-layout

regions[principal]		= Barra Superior
regions[branding]       = Marca
regions[navigation]     = Barra de Navegación
regions[highlighted]    = Destacado
regions[help]           = Ayuda
regions[slider]			= Slider
regions[content]        = Contenido
regions[sidebar_first]  = Barra Lateral
regions[footer]         = Footer


; Stylesheets
stylesheets[all][] = css/layouts/home/home.layout.css
stylesheets[all][] = css/layouts/home/home.layout.no-query.css
stylesheets[all][] = css/layouts/home/verdechile-home.layout.css
